{"name": "test_create_double_user_error", "status": "passed", "description": "Попытка создать пользователя, который уже зарегистрирован посредством фмкстуры", "attachments": [{"name": "stdout", "source": "42b38d4e-1c48-477d-8e39-3c0ad189ce31-attachment.txt", "type": "text/plain"}], "start": 1709739024226, "stop": 1709739025085, "uuid": "a4f145f6-2b49-4e16-bb3a-f41fac32b86b", "historyId": "b0eea2d76d8be485f545edc34842e76b", "testCaseId": "b0eea2d76d8be485f545edc34842e76b", "fullName": "tests.test_creating_user.TestCreatingUser#test_create_double_user_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_creating_user"}, {"name": "subSuite", "value": "TestCreatingUser"}, {"name": "host", "value": "MSK-PC777"}, {"name": "thread", "value": "4380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_creating_user"}]}