{"name": "test_login_user_error", "status": "passed", "description": "Авторизация под неверным логином и паролем", "start": 1710229303799, "stop": 1710229304377, "uuid": "168b031b-8870-46a3-82dc-7499a6fe9c4c", "historyId": "2255ee234cfcd5d264bf7ed07b43520b", "testCaseId": "2255ee234cfcd5d264bf7ed07b43520b", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "MSK-PC777"}, {"name": "thread", "value": "15184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}